/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApproachSection: typeof import('./src/components/landing/ApproachSection.vue')['default']
    AudienceSection: typeof import('./src/components/landing/AudienceSection.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    CallToActionSection: typeof import('./src/components/landing/CallToActionSection.vue')['default']
    Card: typeof import('primevue/card')['default']
    Drawer: typeof import('primevue/drawer')['default']
    DrawerNavItem: typeof import('./src/components/DrawerNavItem.vue')['default']
    FeatureCard: typeof import('./src/components/landing/FeatureCard.vue')['default']
    FeaturesSection: typeof import('./src/components/landing/FeaturesSection.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    FooterSection: typeof import('./src/components/landing/FooterSection.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    HeroSection: typeof import('./src/components/landing/HeroSection.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LandingFeatures: typeof import('./src/components/landing/LandingFeatures.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    NavBar: typeof import('./src/components/landing/NavBar.vue')['default']
    Password: typeof import('primevue/password')['default']
    PhilosophySection: typeof import('./src/components/landing/PhilosophySection.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SearchFilter: typeof import('./src/components/SearchFilter.vue')['default']
    SidebarDrawer: typeof import('./src/components/SidebarDrawer.vue')['default']
    SidebarNav: typeof import('./src/components/SidebarNav.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface GlobalDirectives {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
    Ripple: typeof import('primevue/ripple')['default']
  }
}
