/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApproachSection: typeof import('./src/components/landing/ApproachSection.vue')['default']
    AudienceSection: typeof import('./src/components/landing/AudienceSection.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    CallToActionSection: typeof import('./src/components/landing/CallToActionSection.vue')['default']
    Card: typeof import('primevue/card')['default']
    FeatureCard: typeof import('./src/components/landing/FeatureCard.vue')['default']
    FeaturesSection: typeof import('./src/components/landing/FeaturesSection.vue')['default']
    FooterSection: typeof import('./src/components/landing/FooterSection.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    HeroSection: typeof import('./src/components/landing/HeroSection.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LandingFeatures: typeof import('./src/components/landing/LandingFeatures.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    NavBar: typeof import('./src/components/landing/NavBar.vue')['default']
    PhilosophySection: typeof import('./src/components/landing/PhilosophySection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface GlobalDirectives {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
    Ripple: typeof import('primevue/ripple')['default']
  }
}
