/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddSolutionModal: typeof import('./src/components/problem-show/AddSolutionModal.vue')['default']
    ApproachSection: typeof import('./src/components/landing/ApproachSection.vue')['default']
    AudienceSection: typeof import('./src/components/landing/AudienceSection.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    CallToActionSection: typeof import('./src/components/landing/CallToActionSection.vue')['default']
    Card: typeof import('primevue/card')['default']
    DashboardHeader: typeof import('./src/components/dashboard/DashboardHeader.vue')['default']
    DashboardToday: typeof import('./src/components/dashboard/DashboardToday.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DifficultyTag: typeof import('./src/components/DifficultyTag.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    DrawerNavItem: typeof import('./src/components/DrawerNavItem.vue')['default']
    FeatureCard: typeof import('./src/components/landing/FeatureCard.vue')['default']
    FeaturesSection: typeof import('./src/components/landing/FeaturesSection.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    FooterSection: typeof import('./src/components/landing/FooterSection.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    GradeItem: typeof import('./src/components/dashboard/dialog/GradeItem.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    HeroSection: typeof import('./src/components/landing/HeroSection.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InitialReviewModal: typeof import('./src/components/problem-show/InitialReviewModal.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LandingFeatures: typeof import('./src/components/landing/LandingFeatures.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    NavBar: typeof import('./src/components/landing/NavBar.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    PhilosophySection: typeof import('./src/components/landing/PhilosophySection.vue')['default']
    ProblemCard: typeof import('./src/components/dashboard/ProblemCard.vue')['default']
    ProblemTag: typeof import('./src/components/ProblemTag.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    QuestionSection: typeof import('./src/components/problem-show/QuestionSection.vue')['default']
    ReviewDialog: typeof import('./src/components/dashboard/dialog/ReviewDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    SearchBar: typeof import('./src/components/dashboard/SearchBar.vue')['default']
    SearchFilter: typeof import('./src/components/dashboard/SearchFilter.vue')['default']
    SidebarDrawer: typeof import('./src/components/SidebarDrawer.vue')['default']
    SidebarNav: typeof import('./src/components/SidebarNav.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SkeletonLoader: typeof import('./src/components/problem-show/SkeletonLoader.vue')['default']
    SolutionSection: typeof import('./src/components/problem-show/SolutionSection.vue')['default']
    SuggestedProblems: typeof import('./src/components/dashboard/SuggestedProblems.vue')['default']
    TextArea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    TodaysProgress: typeof import('./src/components/dashboard/TodaysProgress.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface GlobalDirectives {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
    Ripple: typeof import('primevue/ripple')['default']
  }
}
